name: Securities Disabled Kernel Build Enforcing

on:
  workflow_dispatch:

jobs:
  enforcing:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo timedatectl set-timezone Asia/Jakarta
          sudo apt-get update
          sudo apt-get install -y \
            ccache \
            python3 \
            brotli \
            zip \
            zstd \
            tar \
            lz4 \
            cpio \
            xz-utils \
            pahole \
            libelf-dev

          DIR="$(readlink -f .)"
          PARENT_DIR="$(readlink -f "${DIR}/..")"

          git clone --depth=1 \
            https://gitlab.com/tejas101k/clang-r450784d.git \
            "$PARENT_DIR/clang-r450784d"

      - name: Setup mold linker
        uses: rui314/setup-mold@v1

      - name: Build kernel
        run: |
          bash buildnoavb.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Enforcing-NoSecurities
          path: |
            kernel_build/germanium*
